version: '3.1'
services:
  web:
    image: dingowithfun/odoo-custom:latest  # Tu imagen personalizada en Docker Hub
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - /home/edurobrus/Documentos/GitHub/CARPETA_OODDO/addons:/mnt/extra-addons  # Monta tu carpeta local de addons en el contenedor
  mydb:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data  # Volumen persistente para la base de datos

volumes:
  odoo-db-data:
